/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (coord E10), U7[4]/UART0_RX
  @{ */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_PERIPHERAL UART0       /*!<@brief Device name: UART0 */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_SIGNAL RX              /*!<@brief UART0 signal: RX */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_PIN 16U                /*!<@brief PORTB pin index: 16 */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_PIN_NAME UART0_RX      /*!<@brief Pin name */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_LABEL "U7[4]/UART0_RX" /*!<@brief Label */
#define DEBUGUART_INITPINS_DEBUG_UART_RX_NAME "DEBUG_UART_RX"   /*!<@brief Identifier name */
                                                                /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_PERIPHERAL UART0        /*!<@brief Device name: UART0 */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_SIGNAL TX               /*!<@brief UART0 signal: TX */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_PORT PORTB              /*!<@brief PORT device name: PORTB */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_PIN 17U                 /*!<@brief PORTB pin index: 17 */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_PIN_NAME UART0_TX       /*!<@brief Pin name */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_LABEL "U10[1]/UART0_TX" /*!<@brief Label */
#define DEBUGUART_INITPINS_DEBUG_UART_TX_NAME "DEBUG_UART_TX"    /*!<@brief Identifier name */
                                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void DebugUART_InitPins(void);

/*! @name PORTA29 (coord H11), U19[3]/FXAS21002_INT1
  @{ */
#define NINEDOF_INITPINS_GYRO_INT1_PERIPHERAL GPIOA              /*!<@brief Device name: GPIOA */
#define NINEDOF_INITPINS_GYRO_INT1_SIGNAL GPIO                   /*!<@brief GPIOA signal: GPIO */
#define NINEDOF_INITPINS_GYRO_INT1_GPIO GPIOA                    /*!<@brief GPIO device name: GPIOA */
#define NINEDOF_INITPINS_GYRO_INT1_GPIO_PIN 29U                  /*!<@brief PORTA pin index: 29 */
#define NINEDOF_INITPINS_GYRO_INT1_PORT PORTA                    /*!<@brief PORT device name: PORTA */
#define NINEDOF_INITPINS_GYRO_INT1_PIN 29U                       /*!<@brief PORTA pin index: 29 */
#define NINEDOF_INITPINS_GYRO_INT1_CHANNEL 29                    /*!<@brief GPIOA GPIO channel: 29 */
#define NINEDOF_INITPINS_GYRO_INT1_PIN_NAME PTA29                /*!<@brief Pin name */
#define NINEDOF_INITPINS_GYRO_INT1_LABEL "U19[3]/FXAS21002_INT1" /*!<@brief Label */
#define NINEDOF_INITPINS_GYRO_INT1_NAME "GYRO_INT1"              /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name PORTA28 (coord H12), U19[2]/FXAS21002_INT2
  @{ */
#define NINEDOF_INITPINS_GYRO_INT2_PERIPHERAL GPIOA              /*!<@brief Device name: GPIOA */
#define NINEDOF_INITPINS_GYRO_INT2_SIGNAL GPIO                   /*!<@brief GPIOA signal: GPIO */
#define NINEDOF_INITPINS_GYRO_INT2_GPIO GPIOA                    /*!<@brief GPIO device name: GPIOA */
#define NINEDOF_INITPINS_GYRO_INT2_GPIO_PIN 28U                  /*!<@brief PORTA pin index: 28 */
#define NINEDOF_INITPINS_GYRO_INT2_PORT PORTA                    /*!<@brief PORT device name: PORTA */
#define NINEDOF_INITPINS_GYRO_INT2_PIN 28U                       /*!<@brief PORTA pin index: 28 */
#define NINEDOF_INITPINS_GYRO_INT2_CHANNEL 28                    /*!<@brief GPIOA GPIO channel: 28 */
#define NINEDOF_INITPINS_GYRO_INT2_PIN_NAME PTA28                /*!<@brief Pin name */
#define NINEDOF_INITPINS_GYRO_INT2_LABEL "U19[2]/FXAS21002_INT2" /*!<@brief Label */
#define NINEDOF_INITPINS_GYRO_INT2_NAME "GYRO_INT2"              /*!<@brief Identifier name */
                                                                 /* @} */

/*! @name PORTC17 (coord D5), U8[11]/FXOS8700CQ_INT1
  @{ */
#define NINEDOF_INITPINS_ACCEL_INT1_PERIPHERAL GPIOC               /*!<@brief Device name: GPIOC */
#define NINEDOF_INITPINS_ACCEL_INT1_SIGNAL GPIO                    /*!<@brief GPIOC signal: GPIO */
#define NINEDOF_INITPINS_ACCEL_INT1_GPIO GPIOC                     /*!<@brief GPIO device name: GPIOC */
#define NINEDOF_INITPINS_ACCEL_INT1_GPIO_PIN 17U                   /*!<@brief PORTC pin index: 17 */
#define NINEDOF_INITPINS_ACCEL_INT1_PORT PORTC                     /*!<@brief PORT device name: PORTC */
#define NINEDOF_INITPINS_ACCEL_INT1_PIN 17U                        /*!<@brief PORTC pin index: 17 */
#define NINEDOF_INITPINS_ACCEL_INT1_CHANNEL 17                     /*!<@brief GPIOC GPIO channel: 17 */
#define NINEDOF_INITPINS_ACCEL_INT1_PIN_NAME PTC17                 /*!<@brief Pin name */
#define NINEDOF_INITPINS_ACCEL_INT1_LABEL "U8[11]/FXOS8700CQ_INT1" /*!<@brief Label */
#define NINEDOF_INITPINS_ACCEL_INT1_NAME "ACCEL_INT1"              /*!<@brief Identifier name */
                                                                   /* @} */

/*! @name PORTC13 (coord D6), U8[9]/FXOS8700CQ_INT2
  @{ */
#define NINEDOF_INITPINS_ACCEL_INT2_PERIPHERAL GPIOC              /*!<@brief Device name: GPIOC */
#define NINEDOF_INITPINS_ACCEL_INT2_SIGNAL GPIO                   /*!<@brief GPIOC signal: GPIO */
#define NINEDOF_INITPINS_ACCEL_INT2_GPIO GPIOC                    /*!<@brief GPIO device name: GPIOC */
#define NINEDOF_INITPINS_ACCEL_INT2_GPIO_PIN 13U                  /*!<@brief PORTC pin index: 13 */
#define NINEDOF_INITPINS_ACCEL_INT2_PORT PORTC                    /*!<@brief PORT device name: PORTC */
#define NINEDOF_INITPINS_ACCEL_INT2_PIN 13U                       /*!<@brief PORTC pin index: 13 */
#define NINEDOF_INITPINS_ACCEL_INT2_CHANNEL 13                    /*!<@brief GPIOC GPIO channel: 13 */
#define NINEDOF_INITPINS_ACCEL_INT2_PIN_NAME PTC13                /*!<@brief Pin name */
#define NINEDOF_INITPINS_ACCEL_INT2_LABEL "U8[9]/FXOS8700CQ_INT2" /*!<@brief Label */
#define NINEDOF_INITPINS_ACCEL_INT2_NAME "ACCEL_INT2"             /*!<@brief Identifier name */
                                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void NineDoF_InitPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC3 (coord A11), J1[2]/UART1_RX/FTM0_CH2/CLKOUT
  @{ */
#define JETSONTK1_INITPINS_UART1_RX_PERIPHERAL UART1                       /*!<@brief Device name: UART1 */
#define JETSONTK1_INITPINS_UART1_RX_SIGNAL RX                              /*!<@brief UART1 signal: RX */
#define JETSONTK1_INITPINS_UART1_RX_PORT PORTC                             /*!<@brief PORT device name: PORTC */
#define JETSONTK1_INITPINS_UART1_RX_PIN 3U                                 /*!<@brief PORTC pin index: 3 */
#define JETSONTK1_INITPINS_UART1_RX_PIN_NAME UART1_RX                      /*!<@brief Pin name */
#define JETSONTK1_INITPINS_UART1_RX_LABEL "J1[2]/UART1_RX/FTM0_CH2/CLKOUT" /*!<@brief Label */
#define JETSONTK1_INITPINS_UART1_RX_NAME "UART1_RX"                        /*!<@brief Identifier name */
                                                                           /* @} */

/*! @name PORTC4 (coord A9), J1[4]/UART1_TX/FTM0_CH3/FB_AD11
  @{ */
#define JETSONTK1_INITPINS_UART1_TX_PERIPHERAL UART1                        /*!<@brief Device name: UART1 */
#define JETSONTK1_INITPINS_UART1_TX_SIGNAL TX                               /*!<@brief UART1 signal: TX */
#define JETSONTK1_INITPINS_UART1_TX_PORT PORTC                              /*!<@brief PORT device name: PORTC */
#define JETSONTK1_INITPINS_UART1_TX_PIN 4U                                  /*!<@brief PORTC pin index: 4 */
#define JETSONTK1_INITPINS_UART1_TX_PIN_NAME UART1_TX                       /*!<@brief Pin name */
#define JETSONTK1_INITPINS_UART1_TX_LABEL "J1[4]/UART1_TX/FTM0_CH3/FB_AD11" /*!<@brief Label */
#define JETSONTK1_INITPINS_UART1_TX_NAME "UART1_TX"                         /*!<@brief Identifier name */
#define JETSONTK1_INITPINS_UART1_TX_DIRECTION kPIN_MUX_DirectionOutput      /*!<@brief Direction */
                                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void JetsonTK1_InitPins(void);

/*! @name PORTA25 (coord J12), J1[16]/CMP3_IN5
  @{ */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_PERIPHERAL GPIOA                   /*!<@brief Device name: GPIOA */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_SIGNAL GPIO                        /*!<@brief GPIOA signal: GPIO */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_GPIO GPIOA                         /*!<@brief GPIO device name: GPIOA */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_GPIO_PIN 25U                       /*!<@brief PORTA pin index: 25 */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_PORT PORTA                         /*!<@brief PORT device name: PORTA */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_PIN 25U                            /*!<@brief PORTA pin index: 25 */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_CHANNEL 25                         /*!<@brief GPIOA GPIO channel: 25 */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_PIN_NAME PTA25                     /*!<@brief Pin name */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_LABEL "J1[16]/CMP3_IN5"            /*!<@brief Label */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_NAME "CMP3_IN5"                    /*!<@brief Identifier name */
#define DUALHBRIDGE_INITPINS_CMP3_IN5_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                         /* @} */

/*! @name PORTC2 (coord A12), J1[14]/FTM0_CH1/CMP1_IN0/FB_AD12
  @{ */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_PERIPHERAL GPIOC                         /*!<@brief Device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_SIGNAL GPIO                              /*!<@brief GPIOC signal: GPIO */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_GPIO GPIOC                               /*!<@brief GPIO device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_GPIO_PIN 2U                              /*!<@brief PORTC pin index: 2 */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_PORT PORTC                               /*!<@brief PORT device name: PORTC */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_PIN 2U                                   /*!<@brief PORTC pin index: 2 */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_CHANNEL 2                                /*!<@brief GPIOC GPIO channel: 2 */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_PIN_NAME PTC2                            /*!<@brief Pin name */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_LABEL "J1[14]/FTM0_CH1/CMP1_IN0/FB_AD12" /*!<@brief Label */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_NAME "FTM0_CH1"                          /*!<@brief Identifier name */
#define DUALHBRIDGE_INITPINS_FTM0_CH1_DIRECTION kPIN_MUX_DirectionOutput       /*!<@brief Direction */
                                                                               /* @} */

/*! @name PORTC5 (coord D8), J1[12]/I2S0_RXD0/FB_AD10/FTM0_CH2
  @{ */
#define DUALHBRIDGE_INITPINS_FB_AD10_PERIPHERAL GPIOC                          /*!<@brief Device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FB_AD10_SIGNAL GPIO                               /*!<@brief GPIOC signal: GPIO */
#define DUALHBRIDGE_INITPINS_FB_AD10_GPIO GPIOC                                /*!<@brief GPIO device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FB_AD10_GPIO_PIN 5U                               /*!<@brief PORTC pin index: 5 */
#define DUALHBRIDGE_INITPINS_FB_AD10_PORT PORTC                                /*!<@brief PORT device name: PORTC */
#define DUALHBRIDGE_INITPINS_FB_AD10_PIN 5U                                    /*!<@brief PORTC pin index: 5 */
#define DUALHBRIDGE_INITPINS_FB_AD10_CHANNEL 5                                 /*!<@brief GPIOC GPIO channel: 5 */
#define DUALHBRIDGE_INITPINS_FB_AD10_PIN_NAME PTC5                             /*!<@brief Pin name */
#define DUALHBRIDGE_INITPINS_FB_AD10_LABEL "J1[12]/I2S0_RXD0/FB_AD10/FTM0_CH2" /*!<@brief Label */
#define DUALHBRIDGE_INITPINS_FB_AD10_NAME "FB_AD10"                            /*!<@brief Identifier name */
#define DUALHBRIDGE_INITPINS_FB_AD10_DIRECTION kPIN_MUX_DirectionOutput        /*!<@brief Direction */
                                                                               /* @} */

/*! @name PORTC12 (coord A7), J1[10]/FB_AD27
  @{ */
#define DUALHBRIDGE_INITPINS_FB_AD27_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FB_AD27_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define DUALHBRIDGE_INITPINS_FB_AD27_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define DUALHBRIDGE_INITPINS_FB_AD27_GPIO_PIN 12U                       /*!<@brief PORTC pin index: 12 */
#define DUALHBRIDGE_INITPINS_FB_AD27_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define DUALHBRIDGE_INITPINS_FB_AD27_PIN 12U                            /*!<@brief PORTC pin index: 12 */
#define DUALHBRIDGE_INITPINS_FB_AD27_CHANNEL 12                         /*!<@brief GPIOC GPIO channel: 12 */
#define DUALHBRIDGE_INITPINS_FB_AD27_PIN_NAME PTC12                     /*!<@brief Pin name */
#define DUALHBRIDGE_INITPINS_FB_AD27_LABEL "J1[10]/FB_AD27"             /*!<@brief Label */
#define DUALHBRIDGE_INITPINS_FB_AD27_NAME "FB_AD27"                     /*!<@brief Identifier name */
#define DUALHBRIDGE_INITPINS_FB_AD27_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void DualHBridge_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
